### ISSUE TITLE
Separate HTML file and give path to that HTML

### ISSUE THREAD

**Issue by shivampandey2021** [Nicholaiii/handlebars-pdf#2]
How can I separate HTML file and give path to that HTML ?

**Comment by Nicholaiii** [comment]
Are you looking to use an HTML file instead of just a text template?
```js
const fs = require('fs')

let document = {
  template: fs.readFileSync('document.html', 'utf8'),
  context: {
    msg: 'Hello world'
  },
  path: "./test-"+Math.random()+".pdf"
}
```

This assumes your file is saved in utf8

**Comment by shivampandey2021** [comment]
Thanks for your response.

After using a separate html file the content does not fit to pdf page When I am running it on PRODUCTION. The width of the content is more than the pdf page and content got cut from the right side.
Any help?
